# Using a node runtime as our parent image 
# this includes linux, this is a base image available within docker
FROM node:18

# Setting the working directory for our app: (Where we are working from)
WORKDIR /app

# Copying our package over:

# Install ffmpeg in the container
RUN apt-get update && apt-get install -y ffmpeg

# Copy package.json and package-lock.json into the working directory
COPY package*.json ./

# Install any needed packages specified in package.json
RUN npm install

# Copy app source inside the docker image
COPY . .

# Make port 3000 available outside this container
EXPOSE 3000

# Define the command to run your app using CMD (only one CMD allowed)
CMD [ "npm", "start" ]